-- DO NOT EDIT THIS FILE
--
-- We use hspec-discover to automatically discover hspec tests. The tests
-- are provided in files that has the name FooSpec.hs.
--
-- See https://hspec.github.io/hspec-discover.html
--
{-# OPTIONS_GHC -F -pgmF hspec-discover #-}
